---
# file: roles/template/tasks/delete-mount-points.yml

- name: delete folder {{ rook_ceph.dataDirHostPath }}
  file:
    path: "{{ rook_ceph.dataDirHostPath }}"
    state: absent
  become: true

- name: delete folder {{ rook_ceph.storagePath }}
  file:
    path: "{{ rook_ceph.storagePath }}"
    state: absent
  become: true
  when: rook_ceph.useDirectories

- name: get rook-ceph volume group
  shell: |
    pvdisplay {{ rook_ceph.device }}|grep "VG Name"|grep "ceph-"|awk '{print $3;}'
  register: vgname

- name: rook-ceph vg remove and wipe device
  shell: |
    vgremove {{ vgname.stdout }} -f
    dd if=/dev/zero of={{ rook_ceph.device }} count=1 bs=1k
  become: true
  ignore_errors: yes
  when: vgname.stdout != ""


