---
# file: roles/template/tasks/install-mount-points.yml

- name: create folder {{ rook_ceph.dataDirHostPath }}
  file:
    path: "{{ rook_ceph.dataDirHostPath }}"
    state: directory
    mode: '0755'
  become: true

