---
# file: roles/gitea/tasks/delete-gitea.yml

- name: delete ui nginx ingress
  shell: kubectl delete -f /home/kubeadmin/gitea/gitea-nginx.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/gitea/gitea-deployment.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/gitea/gitea-deployment.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/gitea/gitea-pvc.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/gitea/gitea-pvc.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/gitea/gitea-service.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/gitea/gitea-service.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: true
