---
# file: roles/gitea/tasks/delete-namespace.yml

- name: delete gitea namespace "{{ gitea.namespace }}"
  shell: |
    kubectl delete namespace {{ gitea.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true
