---
# file: roles/gitea/tasks/install.yml

- include_tasks: "roles/gitea/tasks/install-helm.yml"
  when: task == "helm" or task == "all"

- include_tasks: "roles/gitea/tasks/install-repo.yml"
  when: task == "repo" or task == "all"

- include_tasks: "roles/gitea/tasks/install-namespace.yml"
  when: task == "namespace" or task == "all"

- include_tasks: "roles/gitea/tasks/install-stolon.yml"
  when: (task == "stolon" or task == "all") and gitea.stolon.enabled

- include_tasks: "roles/gitea/tasks/install-cfssl.yml"
  when: task == "cfssl" or task == "all"

- include_tasks: "roles/gitea/tasks/install-gitea.yml"
  when: task == "gitea" or task == "all"
