---
# file: roles/rook-ceph/tasks/delete-label-nodes.yml

- name: "delete label rook-ceph nodes {{ rook_ceph.label.nodes_key }}:{{ rook_ceph.label.nodes_value }}"
  shell: |
    kubectl label nodes {{ item }} {{ rook_ceph.label.nodes_key }}-
  become: true
  become_user: kubeadmin
  vars:
  with_items: "{{ rook_ceph.nodes }}"
  ignore_errors: yes