---
# file: roles/rook-ceph/tasks/delete-toolbox.yml

- name: delete rook-ceph toolbox
  shell: |
    cd /home/kubeadmin/rook-ceph/cluster/examples/kubernetes/ceph
    kubectl delete -f toolbox.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: yes
