---
# file: roles/rook-ceph/tasks/install-storage-class.yml

- name: create file /home/kubeadmin/rook-ceph/storageclass.yaml
  copy:
    dest: /home/kubeadmin/rook-ceph/storageclass.yaml
    content: |
      apiVersion: ceph.rook.io/v1
      kind: CephBlockPool
      metadata:
        name: replicapool
        namespace: rook-ceph
      spec:
        failureDomain: host
        replicated:
          size: {{ rook_ceph.count.replica }}
      ---
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: rook-ceph-block
      provisioner: rook-ceph.rbd.csi.ceph.com
      parameters:
          clusterID: rook-ceph
          pool: replicapool
          imageFormat: "2"
          imageFeatures: layering
          csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
          csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
          csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
          csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
          csi.storage.k8s.io/fstype: ext4
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
  become: true
  become_user: kubeadmin

- name: install rook-ceph new storage class "rook-ceph-block"
  shell: |
    cd /home/kubeadmin/rook-ceph
    kubectl apply -f storageclass.yaml
  become: true
  become_user: kubeadmin

- name: set "rook-ceph-block" as default Storage Class
  shell: 'kubectl patch storageclass rook-ceph-block -p "{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}"'
  become: true
  become_user: kubeadmin

