---
# file: roles/rook-ceph/tasks/install-toolbox.yml

- name: install rook-ceph toolbox
  shell: |
    cd /home/kubeadmin/rook-ceph/cluster/examples/kubernetes/ceph
    kubectl apply -f toolbox.yaml
  become: true
  become_user: kubeadmin
