---
# file: roles/keycloak/tasks/delete-ui.yml

- name: delete secret tls-secret-keycloak
  shell: |
    kubectl delete secret  tls-secret-keycloak -n {{ keycloak.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/keycloak/ingress-keycloak.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/keycloak/ingress-keycloak.yaml 
  become: true
  become_user: kubeadmin
  ignore_errors: true
