---
# file: roles/keycloak/tasks/delete.yml

- include_tasks: "roles/keycloak/tasks/delete-ui.yml"
  when: task == "ui" or task == "all"

- include_tasks: "roles/keycloak/tasks/delete-keycloak.yml"
  when: task == "keycloak" or task == "all"

- include_tasks: "roles/keycloak/tasks/delete-stolon.yml"
  when: task == "stolon" or task == "all"

- include_tasks: "roles/keycloak/tasks/delete-namespace.yml"
  when: task == "namespace" or task == "all"

- include_tasks: "roles/keycloak/tasks/delete-repo.yml"
  when: task == "repo" or task == "all"





