---
# file: roles/nexus/tasks/delete-ui.yml

- name: delete secret tls-secret-nexus
  shell: |
    kubectl delete secret  tls-secret-nexus -n {{ nexus.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/nexus/ingress-nexus.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/nexus/ingress-nexus.yaml 
  become: true
  become_user: kubeadmin
  ignore_errors: true
