---
# file: roles/nexus/tasks/delete-namespace.yml

- name: delete nexus namespace "{{ nexus.namespace }}"
  shell: |
    kubectl nexus namespace {{ nexus.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true
