---
# file: roles/nexus/tasks/delete.yml

- include_tasks: "roles/nexus/tasks/delete-ui.yml"
  when: task == "ui" or task == "all"

- include_tasks: "roles/nexus/tasks/delete-nexus.yml"
  when: task == "nexus" or task == "all"

- include_tasks: "roles/nexus/tasks/delete-namespace.yml"
  when: task == "namespace" or task == "all"

- include_tasks: "roles/nexus/tasks/delete-repo.yml"
  when: task == "repo" or task == "all"





