---
# file: roles/drone/tasks/delete.yml

- include_tasks: "roles/drone/tasks/delete-drone-runner.yml"
  when: task == "drone-runner" or task == "all"

- include_tasks: "roles/drone/tasks/delete-drone.yml"
  when: task == "drone" or task == "all"

- include_tasks: "roles/drone/tasks/delete-cfssl.yml"
  when: task == "cfssl" or task == "all"

- include_tasks: "roles/drone/tasks/delete-repo.yml"
  when: task == "repo" or task == "all"

- include_tasks: "roles/drone/tasks/delete-stolon.yml"
  when: task == "stolon" or task == "all"

- include_tasks: "roles/drone/tasks/delete-namespace.yml"
  when: task == "namespace" or task == "all"

