---
# file: roles/drone/tasks/delete-namespace.yml

- name: delete gitea namespace "{{ drone.namespace }}"
  shell: |
    kubectl delete namespace {{ drone.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true
