---
# file: roles/drone/tasks/install.yml

- include_tasks: "roles/drone/tasks/install-helm.yml"
  when: task == "helm" or task == "all"

- include_tasks: "roles/drone/tasks/install-repo.yml"
  when: task == "repo" or task == "all"

- include_tasks: "roles/drone/tasks/install-namespace.yml"
  when: task == "namespace" or task == "all"

- include_tasks: "roles/drone/tasks/install-stolon.yml"
  when: task == "stolon" or task == "all"

- include_tasks: "roles/drone/tasks/install-cfssl.yml"
  when: task == "cfssl" or task == "all"

- include_tasks: "roles/drone/tasks/install-drone.yml"
  when: task == "drone" or task == "all"
