---
# file: roles/prometheus/tasks/grafana-ui-install.yml

- name: create file /home/kubeadmin/cfssl/grafana-csr.json
  copy:
    content: |
      {
          "CN": "{{ grafana.ui.csr_CN }}",
          "hosts": [
              "{{ grafana.ui.host }}"
          ],
          "key": {
              "algo": "rsa",
              "size": 2048
          },
          "names": [
              {
                  "C": "{{ grafana.ca.csr_C }}",
                  "L": "{{ grafana.ca.csr_L }}",
                  "ST": "{{ grafana.ca.csr_ST }}"
              }
          ]
      }
    dest: /home/kubeadmin/cfssl/grafana-csr.json
  become: true
  become_user: kubeadmin

- name: cfssl gencert
  shell: |
    cd /home/kubeadmin/cfssl 
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=web-servers grafana-csr.json | cfssljson -bare grafana
  become: true
  become_user: kubeadmin

- name: create secret tls-secret
  shell: |
    cd /home/kubeadmin/cfssl 
    kubectl create secret tls tls-secret --key ./grafana-key.pem --cert grafana.pem -n monitoring
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/prometheus/grafana-nginx.yaml
  copy:
    content: |
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: grafana-nginx
        namespace: monitoring
        annotations:
          kubernetes.io/ingress.class: nginx
      spec:
        tls:
        - secretName: tls-secret
        rules:
        - host: {{ grafana.ui.host }}
          http:
            paths:
            - path: /
              backend:
                serviceName: grafana
                servicePort: 3000
    dest: /home/kubeadmin/prometheus/grafana-nginx.yaml
  become: true
  become_user: kubeadmin

- name: apply ui nginx ingress
  shell: kubectl apply -f /home/kubeadmin/prometheus/grafana-nginx.yaml
  become: true
  become_user: kubeadmin
