---
# file: roles/prometheus/tasks/install-operator.yml

- name: install prometheus operator
  shell: |
    cd /home/kubeadmin/prometheus
    kubectl create -f manifests/setup
    until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
    kubectl create -f manifests/
  become: true
  become_user: kubeadmin

