---
# file: roles/template/tasks/delete.yml

- include_tasks: "roles/template/tasks/delete-step-1.yml"
  when: task == "step-1" or task == "all"

- include_tasks: "roles/template/tasks/delete-step-2.yml"
  when: task == "step-2" or task == "all"
