
# drone configuration

drone:
  namespace: drone
  rpc_secret: CHANGE_ME

  gitea:
    client_id: CHANGE_ME
    client_secret: CHANGE_ME
    server: https://gitea.k8s.europe

  persistence:
    size: 2Gi

  ca:
    csr_C: EU
    csr_L: paris
    csr_ST: france
  ui:
    csr_CN: drone.k8s.europe
    host: drone.k8s.europe
