
# gitea configuration

gitea:
  namespace: gitea

  app: Gitea
  domain: gitea.k8s.europe
  root_url: https://gitea.k8s.europe
  ssh_domain: gitea.k8s.europe
  ssh_external_ip: 192.168.10.190

  webhook:
    skip_tls_verify: true

  db:
    name: gitea
    user: gitea
    password: password

  stolon:
    enabled: true
    release: gitea-stolon
    superuserUsername: postgres
    superuserPassword: password
    replicationPassword: password

    persistence:
      size: 2Gi
    keeper:
      replicaCount: 2
    proxy:
      replicaCount: 2

    affinity:
      enabled: true
      keeper:
        label: gitea-stolon-node/keeper
        nodes: 
          - roma.europe
          - madrid.europe
      proxy:
        label: gitea-stolon-node/proxy
        nodes: 
          - roma.europe
          - madrid.europe
      sentinel:
        label: gitea-stolon-node/sentinel
        nodes: 
          - roma.europe
          - madrid.europe
  ca:
    csr_C: EU
    csr_L: paris
    csr_ST: france
  ui:
    csr_CN: gitea.k8s.europe
    host: gitea.k8s.europe
