
# rook-ceph configuration

rook_ceph:
  dataDirHostPath: /var/lib/rook
  storagePath: /data/rook
  count:
    mon: 3
    osd: 3
    replica: 2
  nodes: 
    - paris.europe
    - berlin.europe
    - roma.europe
  label:
    nodes_key: rook-ceph-node
    nodes_value: storage
  ui:
    csr_CN: rook-ceph.k8s.europe
    host: rook-ceph.k8s.europe
    ca:
      csr_C: EU
      csr_L: paris
      csr_ST: france
