---
# file: minio.yml
- hosts: 
    - kubeadmin
  become: true
  roles:
    - minio
  vars_files:
    - "{{ inventory_dir }}/group_vars/roles/minio.yml"

- hosts: 
    - localhost
  connection: local
  roles:
    - minio
