---
# file: roles/minio/tasks/delete-minio.yml

- name: helm delete {{ minio.helm.name }} --namespace {{ minio.namespace }}
  shell: |
    helm delete {{ minio.helm.name }} --namespace {{ minio.namespace }}
  become: true
  become_user: kubeadmin
  ignore_errors: true
