---
# file: roles/minio/tasks/delete.yml

- include_tasks: "roles/minio/tasks/delete-ui-browser.yml"
  when: task == "ui-browser" or task == "all"

- include_tasks: "roles/minio/tasks/delete-ui-console.yml"
  when: task == "ui-console" or task == "all"

- include_tasks: "roles/minio/tasks/delete-minio.yml"
  when: task == "minio" or task == "all"

- include_tasks: "roles/minio/tasks/delete-cfssl.yml"
  when: task == "cfssl" or task == "all"

- include_tasks: "roles/minio/tasks/delete-namespace.yml"
  when: task == "namespace" or task == "all"

