---
# file: roles/minio/tasks/delete-pv.yml

- name: kubectl delete -f /home/kubeadmin/minio/pv-create....yaml
  shell: |
    kubectl delete -f /home/kubeadmin/minio/pv-create-{{ item.name }}.yaml
  become: true
  become_user: kubeadmin
  vars:
  with_items: "{{ minio.pv.nodes }}"
  ignore_errors: true

- name: kubectl delete -f /home/kubeadmin/minio/local-storage.yaml
  shell: |
    kubectl delete -f /home/kubeadmin/minio/local-storage.yaml
  become: true
  become_user: kubeadmin
  ignore_errors: true

