---
# file: roles/minio/tasks/install-cfssl.yml

- name: create file /home/kubeadmin/cfssl/minio-browser-csr.json
  copy:
    content: |
      {
          "CN": "{{ minio.tls.browser.csr_CN }}",
          "hosts": [
              "{{ minio.tls.browser.host }}"
          ],
          "key": {
              "algo": "rsa",
              "size": 2048
          },
          "names": [
              {
                  "C": "{{ minio.tls.ca.csr_C }}",
                  "L": "{{ minio.tls.ca.csr_L }}",
                  "ST": "{{ minio.tls.ca.csr_ST }}"
              }
          ]
      }
    dest: /home/kubeadmin/cfssl/minio-browser-csr.json
  become: true
  become_user: kubeadmin

- name: cfssl gencert
  shell: |
    cd /home/kubeadmin/cfssl 
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=web-servers minio-browser-csr.json | cfssljson -bare minio-browser
  become: true
  become_user: kubeadmin

- name: create secret tls-secret-browser
  shell: |
    cd /home/kubeadmin/cfssl 
    kubectl create secret tls tls-secret-browser --key ./minio-browser-key.pem --cert minio-browser.pem -n {{ minio.namespace }}
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/cfssl/minio-console-csr.json
  copy:
    content: |
      {
          "CN": "{{ minio.tls.console.csr_CN }}",
          "hosts": [
              "{{ minio.tls.console.host }}"
          ],
          "key": {
              "algo": "rsa",
              "size": 2048
          },
          "names": [
              {
                  "C": "{{ minio.tls.ca.csr_C }}",
                  "L": "{{ minio.tls.ca.csr_L }}",
                  "ST": "{{ minio.tls.ca.csr_ST }}"
              }
          ]
      }
    dest: /home/kubeadmin/cfssl/minio-console-csr.json
  become: true
  become_user: kubeadmin

- name: cfssl gencert
  shell: |
    cd /home/kubeadmin/cfssl 
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=web-servers minio-console-csr.json | cfssljson -bare minio-console
  become: true
  become_user: kubeadmin

- name: create secret tls-secret-console
  shell: |
    cd /home/kubeadmin/cfssl 
    kubectl create secret tls tls-secret-console --key ./minio-console-key.pem --cert minio-console.pem -n {{ minio.namespace }}
  become: true
  become_user: kubeadmin

- name: create file /home/kubeadmin/cfssl/minio-csr.json
  copy:
    content: |
      {
          "CN": "{{ minio.tls.minio.csr_CN }}",
          "hosts": [
              "{{ minio.tls.minio.host }}"
          ],
          "key": {
              "algo": "rsa",
              "size": 2048
          },
          "names": [
              {
                  "C": "{{ minio.tls.ca.csr_C }}",
                  "L": "{{ minio.tls.ca.csr_L }}",
                  "ST": "{{ minio.tls.ca.csr_ST }}"
              }
          ]
      }
    dest: /home/kubeadmin/cfssl/minio-csr.json
  become: true
  become_user: kubeadmin

- name: cfssl gencert
  shell: |
    cd /home/kubeadmin/cfssl 
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=web-servers minio-csr.json | cfssljson -bare minio
  become: true
  become_user: kubeadmin

- name: create secret generic tls-secret-minio
  shell: |
    cd /home/kubeadmin/cfssl 
    cp ./minio-key.pem ./private.key
    cp ./minio.pem ./public.crt
    kubectl create secret generic tls-secret-minio --from-file private.key --from-file public.crt -n {{ minio.namespace }}
    rm ./private.key
    rm ./public.crt
    kubectl create secret tls tls-secret-minio-ingress --key ./minio-key.pem --cert minio.pem -n {{ minio.namespace }}
  become: true
  become_user: kubeadmin
