---
# file: roles/minio/tasks/install-cfssl-browser.yml

- name: create file /home/kubeadmin/cfssl/minio-browser-csr.json
  copy:
    content: |
      {
          "CN": "{{ minio.tls.browser.csr_CN }}",
          "hosts": [
              "{{ minio.tls.browser.host }}"
          ],
          "key": {
              "algo": "rsa",
              "size": 2048
          },
          "names": [
              {
                  "C": "{{ minio.tls.ca.csr_C }}",
                  "L": "{{ minio.tls.ca.csr_L }}",
                  "ST": "{{ minio.tls.ca.csr_ST }}"
              }
          ]
      }
    dest: /home/kubeadmin/cfssl/minio-browser-csr.json
  become: true
  become_user: kubeadmin

- name: cfssl gencert
  shell: |
    cd /home/kubeadmin/cfssl 
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=web-servers minio-browser-csr.json | cfssljson -bare minio-browser
  become: true
  become_user: kubeadmin

- name: create secret tls-secret-browser
  shell: |
    cd /home/kubeadmin/cfssl 
    kubectl create secret tls tls-secret-browser --key ./minio-browser-key.pem --cert minio-browser.pem -n {{ minio.namespace }}
  become: true
  become_user: kubeadmin
